#!/bin/bash
sudo cp 10-amdgpu.conf_original /usr/share/X11/xorg.conf.d/10-amdgpu.conf
sudo cp 10-nvidia.conf_original /usr/share/X11/xorg.conf.d/10-nvidia.conf

#sudo rm /usr/share/X11/xorg.conf.d/config_nvidia
#sudo cp config_amd /usr/share/X11/xorg.conf.d/config_amd
